#!/usr/bin/env bash

# Wallpaper location
WallpaperPath=~/Pictures/wallpaper

# Legal extensions is png only (delimited by the | char)
WallpaperExt='png'

find -E "$WallpaperPath" -iregex ".*.($WallpaperExt)" |
(
        # Put all files into array
        i=0; while read file; do files[i++]="$file"; done
        
        # Copy a random lines[] element
        cp "${files[$RANDOM % $i]}" /Library/Caches/com.apple.desktop.admin.png
)


